#dist: trusty
#sudo: required

language: python
python:
  - 3.4
  - 3.5
  - 3.6

env:
  global:
    - PIP_DOWNLOAD_CACHE="pip_download_cache"

addons:
  apt:
    sources:
      - sourceline: 'ppa:cleishm/neo4j'
    packages:
      - build-essential
      - libcypher-parser-dev

cache:
  pip: true
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install -Uq pip setuptools coveralls

script:
  - python setup.py test

after_success: coveralls

matrix:
  fast_finish: true

notifications:
  email: false
